//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationMessage", Namespace="http://www.travcorp.com/api/v3")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Playground.ServiceReference1.WSSellingCompanyAuthenticationMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Playground.ServiceReference1.GetToursMessage))]
    public partial class AuthenticationMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApiKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSSellingCompanyAuthenticationMessage", Namespace="http://www.travcorp.com/api/v3")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Playground.ServiceReference1.GetToursMessage))]
    public partial class WSSellingCompanyAuthenticationMessage : Playground.ServiceReference1.AuthenticationMessage {
        
        private string SellingCompanyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SellingCompanyCode {
            get {
                return this.SellingCompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingCompanyCodeField, value) != true)) {
                    this.SellingCompanyCodeField = value;
                    this.RaisePropertyChanged("SellingCompanyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetToursMessage", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    public partial class GetToursMessage : Playground.ServiceReference1.WSSellingCompanyAuthenticationMessage {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Playground.ServiceReference1.TourProduct))]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationInDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationInNightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrochureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrochureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineBookableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTourPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.OperatingProduct OperatingProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.IncludedProducts IncludedProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MVStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string StartCity {
            get {
                return this.StartCityField;
            }
            set {
                if ((object.ReferenceEquals(this.StartCityField, value) != true)) {
                    this.StartCityField = value;
                    this.RaisePropertyChanged("StartCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string EndCity {
            get {
                return this.EndCityField;
            }
            set {
                if ((object.ReferenceEquals(this.EndCityField, value) != true)) {
                    this.EndCityField = value;
                    this.RaisePropertyChanged("EndCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int DurationInDays {
            get {
                return this.DurationInDaysField;
            }
            set {
                if ((this.DurationInDaysField.Equals(value) != true)) {
                    this.DurationInDaysField = value;
                    this.RaisePropertyChanged("DurationInDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int DurationInNights {
            get {
                return this.DurationInNightsField;
            }
            set {
                if ((this.DurationInNightsField.Equals(value) != true)) {
                    this.DurationInNightsField = value;
                    this.RaisePropertyChanged("DurationInNights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string BrochureName {
            get {
                return this.BrochureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureNameField, value) != true)) {
                    this.BrochureNameField = value;
                    this.RaisePropertyChanged("BrochureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string BrochureCode {
            get {
                return this.BrochureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureCodeField, value) != true)) {
                    this.BrochureCodeField = value;
                    this.RaisePropertyChanged("BrochureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool OnlineBookable {
            get {
                return this.OnlineBookableField;
            }
            set {
                if ((this.OnlineBookableField.Equals(value) != true)) {
                    this.OnlineBookableField = value;
                    this.RaisePropertyChanged("OnlineBookable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool IsTourPackage {
            get {
                return this.IsTourPackageField;
            }
            set {
                if ((this.IsTourPackageField.Equals(value) != true)) {
                    this.IsTourPackageField = value;
                    this.RaisePropertyChanged("IsTourPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Playground.ServiceReference1.OperatingProduct OperatingProduct {
            get {
                return this.OperatingProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatingProductField, value) != true)) {
                    this.OperatingProductField = value;
                    this.RaisePropertyChanged("OperatingProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public Playground.ServiceReference1.IncludedProducts IncludedProducts {
            get {
                return this.IncludedProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedProductsField, value) != true)) {
                    this.IncludedProductsField = value;
                    this.RaisePropertyChanged("IncludedProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string MVStatus {
            get {
                return this.MVStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MVStatusField, value) != true)) {
                    this.MVStatusField = value;
                    this.RaisePropertyChanged("MVStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatingProduct", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    public partial class OperatingProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractingSeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StandardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.SellableRoomTypes SellableRoomTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ContractingSeason {
            get {
                return this.ContractingSeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractingSeasonField, value) != true)) {
                    this.ContractingSeasonField = value;
                    this.RaisePropertyChanged("ContractingSeason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificationField, value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string StandardName {
            get {
                return this.StandardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StandardNameField, value) != true)) {
                    this.StandardNameField = value;
                    this.RaisePropertyChanged("StandardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Playground.ServiceReference1.SellableRoomTypes SellableRoomTypes {
            get {
                return this.SellableRoomTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.SellableRoomTypesField, value) != true)) {
                    this.SellableRoomTypesField = value;
                    this.RaisePropertyChanged("SellableRoomTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TourProduct", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    public partial class TourProduct : Playground.ServiceReference1.Product {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="IncludedProducts", Namespace="http://schemas.datacontract.org/2004/07/TTC.iTropics.PublicApiv3.GetTours.Respons" +
        "e", ItemName="IncludedProduct")]
    [System.SerializableAttribute()]
    public class IncludedProducts : System.Collections.Generic.List<Playground.ServiceReference1.IncludedProduct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellableRoomTypes", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    public partial class SellableRoomTypes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SingleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwinShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TripleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TripleShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QuadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QuadShareField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Single {
            get {
                return this.SingleField;
            }
            set {
                if ((this.SingleField.Equals(value) != true)) {
                    this.SingleField = value;
                    this.RaisePropertyChanged("Single");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Twin {
            get {
                return this.TwinField;
            }
            set {
                if ((this.TwinField.Equals(value) != true)) {
                    this.TwinField = value;
                    this.RaisePropertyChanged("Twin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwinShare {
            get {
                return this.TwinShareField;
            }
            set {
                if ((this.TwinShareField.Equals(value) != true)) {
                    this.TwinShareField = value;
                    this.RaisePropertyChanged("TwinShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Triple {
            get {
                return this.TripleField;
            }
            set {
                if ((this.TripleField.Equals(value) != true)) {
                    this.TripleField = value;
                    this.RaisePropertyChanged("Triple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool TripleShare {
            get {
                return this.TripleShareField;
            }
            set {
                if ((this.TripleShareField.Equals(value) != true)) {
                    this.TripleShareField = value;
                    this.RaisePropertyChanged("TripleShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Quad {
            get {
                return this.QuadField;
            }
            set {
                if ((this.QuadField.Equals(value) != true)) {
                    this.QuadField = value;
                    this.RaisePropertyChanged("Quad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool QuadShare {
            get {
                return this.QuadShareField;
            }
            set {
                if ((this.QuadShareField.Equals(value) != true)) {
                    this.QuadShareField = value;
                    this.RaisePropertyChanged("QuadShare");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncludedProduct", Namespace="http://www.travcorp.com/api/v3/GetTours")]
    [System.SerializableAttribute()]
    public partial class IncludedProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ServiceType {
            get {
                return this.ServiceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceTypeField, value) != true)) {
                    this.ServiceTypeField = value;
                    this.RaisePropertyChanged("ServiceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiError", Namespace="http://www.travcorp.com/api/v3")]
    [System.SerializableAttribute()]
    public partial class ApiError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.Errors ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.Errors Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Errors", Namespace="http://www.travcorp.com/api/v3", ItemName="Error")]
    [System.SerializableAttribute()]
    public class Errors : System.Collections.Generic.List<Playground.ServiceReference1.ApiErrorDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiErrorDetail", Namespace="http://www.travcorp.com/api/v3")]
    [System.SerializableAttribute()]
    public partial class ApiErrorDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrochureResponse", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class BrochureResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.Brochure BrochureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.ResponseHeader HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.Brochure Brochure {
            get {
                return this.BrochureField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureField, value) != true)) {
                    this.BrochureField = value;
                    this.RaisePropertyChanged("Brochure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.ResponseHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brochure", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class Brochure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrochureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BrochureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrochureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrochureYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperatingPeriodEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperatingPeriodStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellingCompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SellingPeriodEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SellingPeriodStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandCodeField, value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrochureCode {
            get {
                return this.BrochureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureCodeField, value) != true)) {
                    this.BrochureCodeField = value;
                    this.RaisePropertyChanged("BrochureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BrochureId {
            get {
                return this.BrochureIdField;
            }
            set {
                if ((this.BrochureIdField.Equals(value) != true)) {
                    this.BrochureIdField = value;
                    this.RaisePropertyChanged("BrochureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrochureName {
            get {
                return this.BrochureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureNameField, value) != true)) {
                    this.BrochureNameField = value;
                    this.RaisePropertyChanged("BrochureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrochureYear {
            get {
                return this.BrochureYearField;
            }
            set {
                if ((object.ReferenceEquals(this.BrochureYearField, value) != true)) {
                    this.BrochureYearField = value;
                    this.RaisePropertyChanged("BrochureYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPages {
            get {
                return this.NumberOfPagesField;
            }
            set {
                if ((this.NumberOfPagesField.Equals(value) != true)) {
                    this.NumberOfPagesField = value;
                    this.RaisePropertyChanged("NumberOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperatingPeriodEndDate {
            get {
                return this.OperatingPeriodEndDateField;
            }
            set {
                if ((this.OperatingPeriodEndDateField.Equals(value) != true)) {
                    this.OperatingPeriodEndDateField = value;
                    this.RaisePropertyChanged("OperatingPeriodEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperatingPeriodStartDate {
            get {
                return this.OperatingPeriodStartDateField;
            }
            set {
                if ((this.OperatingPeriodStartDateField.Equals(value) != true)) {
                    this.OperatingPeriodStartDateField = value;
                    this.RaisePropertyChanged("OperatingPeriodStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellingCompanyCode {
            get {
                return this.SellingCompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingCompanyCodeField, value) != true)) {
                    this.SellingCompanyCodeField = value;
                    this.RaisePropertyChanged("SellingCompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SellingPeriodEndDate {
            get {
                return this.SellingPeriodEndDateField;
            }
            set {
                if ((this.SellingPeriodEndDateField.Equals(value) != true)) {
                    this.SellingPeriodEndDateField = value;
                    this.RaisePropertyChanged("SellingPeriodEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SellingPeriodStartDate {
            get {
                return this.SellingPeriodStartDateField;
            }
            set {
                if ((this.SellingPeriodStartDateField.Equals(value) != true)) {
                    this.SellingPeriodStartDateField = value;
                    this.RaisePropertyChanged("SellingPeriodStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIErrorDetail", Namespace="http://www.itropics.com/PublicAPI/Errors")]
    [System.SerializableAttribute()]
    public partial class APIErrorDetail1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrandEnum", Namespace="http://schemas.datacontract.org/2004/07/TTC.iTropics.InternalWSAPI")]
    public enum BrandEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IV = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SH = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationsResponse", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class LocationsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.ResponseHeader HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.MarketVariation[] MarketVariationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.ResponseHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.MarketVariation[] MarketVariations {
            get {
                return this.MarketVariationsField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketVariationsField, value) != true)) {
                    this.MarketVariationsField = value;
                    this.RaisePropertyChanged("MarketVariations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketVariation", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class MarketVariation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsProductCancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Playground.ServiceReference1.Segment[] SegmentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProductCancelled {
            get {
                return this.IsProductCancelledField;
            }
            set {
                if ((this.IsProductCancelledField.Equals(value) != true)) {
                    this.IsProductCancelledField = value;
                    this.RaisePropertyChanged("IsProductCancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Playground.ServiceReference1.Segment[] Segments {
            get {
                return this.SegmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentsField, value) != true)) {
                    this.SegmentsField = value;
                    this.RaisePropertyChanged("Segments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Segment", Namespace="http://www.itropics.com/PublicDataRetrievalAPI")]
    [System.SerializableAttribute()]
    public partial class Segment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LocationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.travcorp.com/publicapi/InternalWSAPI", ConfigurationName="ServiceReference1.IInternalService")]
    public interface IInternalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetToursSellingP" +
            "eriodAgnostic", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetToursSellingP" +
            "eriodAgnosticResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Playground.ServiceReference1.ApiError), Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetToursSellingP" +
            "eriodAgnosticApiErrorFault", Name="ApiError", Namespace="http://www.travcorp.com/api/v3")]
        Playground.ServiceReference1.Product[] GetToursSellingPeriodAgnostic(Playground.ServiceReference1.GetToursMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetToursSellingP" +
            "eriodAgnostic", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetToursSellingP" +
            "eriodAgnosticResponse")]
        System.Threading.Tasks.Task<Playground.ServiceReference1.Product[]> GetToursSellingPeriodAgnosticAsync(Playground.ServiceReference1.GetToursMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochuresByBr" +
            "ochureCodeSellingPeriodAgnostic", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochuresByBr" +
            "ochureCodeSellingPeriodAgnosticResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Playground.ServiceReference1.APIErrorDetail1), Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochuresByBr" +
            "ochureCodeSellingPeriodAgnosticAPIErrorDetailFault", Name="APIErrorDetail", Namespace="http://www.itropics.com/PublicAPI/Errors")]
        Playground.ServiceReference1.BrochureResponse GetBrochuresByBrochureCodeSellingPeriodAgnostic(string brochureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochuresByBr" +
            "ochureCodeSellingPeriodAgnostic", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochuresByBr" +
            "ochureCodeSellingPeriodAgnosticResponse")]
        System.Threading.Tasks.Task<Playground.ServiceReference1.BrochureResponse> GetBrochuresByBrochureCodeSellingPeriodAgnosticAsync(string brochureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/LoadBrochureLook" +
            "upList", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/LoadBrochureLook" +
            "upListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Playground.ServiceReference1.APIErrorDetail1), Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/LoadBrochureLook" +
            "upListAPIErrorDetailFault", Name="APIErrorDetail", Namespace="http://www.itropics.com/PublicAPI/Errors")]
        System.Collections.Generic.Dictionary<string, int> LoadBrochureLookupList(Playground.ServiceReference1.BrandEnum brandEnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/LoadBrochureLook" +
            "upList", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/LoadBrochureLook" +
            "upListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> LoadBrochureLookupListAsync(Playground.ServiceReference1.BrandEnum brandEnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochureDetai" +
            "l", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochureDetai" +
            "lResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Playground.ServiceReference1.APIErrorDetail1), Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochureDetai" +
            "lAPIErrorDetailFault", Name="APIErrorDetail", Namespace="http://www.itropics.com/PublicAPI/Errors")]
        Playground.ServiceReference1.LocationsResponse GetBrochureDetail(int brochureId, string[] catalogCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochureDetai" +
            "l", ReplyAction="http://www.travcorp.com/publicapi/InternalWSAPI/IInternalService/GetBrochureDetai" +
            "lResponse")]
        System.Threading.Tasks.Task<Playground.ServiceReference1.LocationsResponse> GetBrochureDetailAsync(int brochureId, string[] catalogCodes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternalServiceChannel : Playground.ServiceReference1.IInternalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServiceClient : System.ServiceModel.ClientBase<Playground.ServiceReference1.IInternalService>, Playground.ServiceReference1.IInternalService {
        
        public InternalServiceClient() {
        }
        
        public InternalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Playground.ServiceReference1.Product[] GetToursSellingPeriodAgnostic(Playground.ServiceReference1.GetToursMessage request) {
            return base.Channel.GetToursSellingPeriodAgnostic(request);
        }
        
        public System.Threading.Tasks.Task<Playground.ServiceReference1.Product[]> GetToursSellingPeriodAgnosticAsync(Playground.ServiceReference1.GetToursMessage request) {
            return base.Channel.GetToursSellingPeriodAgnosticAsync(request);
        }
        
        public Playground.ServiceReference1.BrochureResponse GetBrochuresByBrochureCodeSellingPeriodAgnostic(string brochureCode) {
            return base.Channel.GetBrochuresByBrochureCodeSellingPeriodAgnostic(brochureCode);
        }
        
        public System.Threading.Tasks.Task<Playground.ServiceReference1.BrochureResponse> GetBrochuresByBrochureCodeSellingPeriodAgnosticAsync(string brochureCode) {
            return base.Channel.GetBrochuresByBrochureCodeSellingPeriodAgnosticAsync(brochureCode);
        }
        
        public System.Collections.Generic.Dictionary<string, int> LoadBrochureLookupList(Playground.ServiceReference1.BrandEnum brandEnum) {
            return base.Channel.LoadBrochureLookupList(brandEnum);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> LoadBrochureLookupListAsync(Playground.ServiceReference1.BrandEnum brandEnum) {
            return base.Channel.LoadBrochureLookupListAsync(brandEnum);
        }
        
        public Playground.ServiceReference1.LocationsResponse GetBrochureDetail(int brochureId, string[] catalogCodes) {
            return base.Channel.GetBrochureDetail(brochureId, catalogCodes);
        }
        
        public System.Threading.Tasks.Task<Playground.ServiceReference1.LocationsResponse> GetBrochureDetailAsync(int brochureId, string[] catalogCodes) {
            return base.Channel.GetBrochureDetailAsync(brochureId, catalogCodes);
        }
    }
}
